version: "3.6"

services:
    redis:
        image: "redis:6.2.5-alpine"
        ports:
            - "6379:6379"
        command: "redis-server"

    app:
        depends_on:
            - redis
        image: "final-project-orchestrator"
        ports:
            - "3000:3000"
        command: "npm run start"
